name: deploy-to gcs

on:
  push:
    branches:
      - main
jobs:
   build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: authenticate to google cloud 
        uses: google-github-actions/auth@v2
        with:
           credentials_json: ${{ secrets.GCP_SA_KEY_JSON}}

      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Build website
        working-directory: ./
        run: npm run build


   
      - name: upload files to gcs
        run: |
            gsutil -m rsync -r ./dist gs://${{ secrets.GCP_BUCKET_NAME }}

      
